flags: {}
packages:
- '.'
resolver: nightly-2019-04-18
extra-deps: []

allow-newer: true

nix:
  packages:
  - zlib
  - pkgconfig
  - ncurses6
  - xorg.libX11
  - xorg.libXext
  - xorg.libXft
  - xorg.libXinerama
  - xorg.libXrandr
  - xorg.libXScrnSaver

